fix: adding missing import statement for rule_helpers in cli.py. This was causing `eventwatcher info` command to fail:
Available Rule Helper Functions:
Traceback (most recent call last):
  File "/av/data/repos/eventwatcher/venv/bin/eventwatcher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/av/data/repos/eventwatcher/venv/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/av/data/repos/eventwatcher/venv/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/av/data/repos/eventwatcher/venv/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/av/data/repos/eventwatcher/venv/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/av/data/repos/eventwatcher/venv/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/av/data/repos/eventwatcher/venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/av/data/repos/eventwatcher/venv/lib/python3.11/site-packages/eventwatcher/cli.py", line 315, in info
    "aggregate_metric": rule_helpers.aggregate_metric,
                        ^^^^^^^^^^^^
NameError: name 'rule_helpers' is not defined